Update site texts
sumelms/website pull request #20
Opened 2020-10-25 18:09 UTC by rluders

I just updated the website texts.

2020-10-25 18:54 UTC, arianerocha requested changes

2020-10-25 18:54 UTC, arianerocha commented on src/pages/index.js
> +      "Customize it, get access to the courses based on your interest, and plan your learning path. The student space is the perfect place to improve the way that you learn while you follow your prog
can you mention about the platform adapting to the student?

2020-10-26 14:35 UTC, arianerocha commented on src/pages/index.js
> +      "The control of the content in your hands. Get statistics about the student progress, and course statistics. Find out how to improve the way that your content is delivered to the students while
`The control of the content in your hands` or `The control of the content is in your hands`?

2020-11-01 09:52 UTC, rluders commented
@arianerocha @mouracamila is it OK for you both? Can we merge it?

2020-11-02 08:14 UTC, merged

2020-11-02 08:15 UTC, rluders commented
I merged the PR, if we need any other fix we can create a new issue, 'cause we didn't have any real text in the website, so... better to have some, even that not perfect, that doesn't had at all.